---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productsbackend # Name of the deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: productsbackend
    spec:
      containers:
      - name: productsbackend
        image: rogerchenacr.azurecr.io/productservice:latest
        ports:
        - containerPort: 80
      env:
      - name: ASPNETCORE_URLS
        value: http://*:80
  selector:
    matchLabels:
      app: productsbackend
---